"""Public workflow API."""

from captioner.media.voice_separation import VoiceSeparationOptions
from captioner.shared.app_paths import ApplicationPaths
from captioner.shared.errors import OperationCancelled
from captioner.shared.logging import LogLevel
from captioner.subtitles.glossary import Glossary, GlossaryEntry
from captioner.subtitles.quality import QualityOptions
from captioner.workflow.application import (
    ApplicationCommand,
    ApplicationPlan,
    ModelStatus,
    download_model,
    execute_doctor,
    execute_refine,
    execute_run,
    execute_transcribe,
    get_application_paths,
    list_models,
    plan_operation,
    resolve_options,
)
from captioner.workflow.doctor import DoctorReport, run_doctor
from captioner.workflow.model_preparation import prepare_asr_model
from captioner.workflow.models import (
    FileFailure,
    ProcessingResult,
    RunResult,
    TranscriptionResult,
    TranscriptionRunResult,
)
from captioner.workflow.options import (
    ASR_PROFILES,
    AsrOptions,
    AsrProfile,
    AudioOptions,
    CleanupOptions,
    ContextAnalysisOptions,
    CorrectionOptions,
    FakeAsrOptions,
    FasterWhisperAsrOptions,
    LlmOptions,
    NemoAsrOptions,
    OutputFormat,
    OutputOptions,
    PipelineOptions,
    Qwen3AsrOptions,
    RepairOptions,
    RunOptions,
    SegmentationOptions,
    TranslationOptions,
    load_options,
    render_options_toml,
    save_options,
    with_asr_profile,
    with_keep_workdir,
)
from captioner.workflow.pipeline import (
    PipelineServices,
    build_fake_services,
    build_services,
    build_subtitle_service,
    discover_inputs,
    process_media,
    run_files,
    transcribe_files,
)
from captioner.workflow.progress import (
    CancellationToken,
    ExecutionContext,
    ProgressEvent,
    ProgressKind,
    ProgressObserver,
    ProgressStage,
)
from captioner.workflow.refine import RefineResult, refine_srt

__all__ = [
    "ASR_PROFILES",
    "ApplicationCommand",
    "ApplicationPaths",
    "ApplicationPlan",
    "AsrOptions",
    "AsrProfile",
    "AudioOptions",
    "CancellationToken",
    "CleanupOptions",
    "ContextAnalysisOptions",
    "CorrectionOptions",
    "DoctorReport",
    "ExecutionContext",
    "FakeAsrOptions",
    "FasterWhisperAsrOptions",
    "FileFailure",
    "Glossary",
    "GlossaryEntry",
    "LlmOptions",
    "LogLevel",
    "ModelStatus",
    "NemoAsrOptions",
    "OperationCancelled",
    "OutputFormat",
    "OutputOptions",
    "PipelineOptions",
    "PipelineServices",
    "ProcessingResult",
    "ProgressEvent",
    "ProgressKind",
    "ProgressObserver",
    "ProgressStage",
    "QualityOptions",
    "Qwen3AsrOptions",
    "RefineResult",
    "RepairOptions",
    "RunOptions",
    "RunResult",
    "SegmentationOptions",
    "TranscriptionResult",
    "TranscriptionRunResult",
    "TranslationOptions",
    "VoiceSeparationOptions",
    "build_fake_services",
    "build_services",
    "build_subtitle_service",
    "discover_inputs",
    "download_model",
    "execute_doctor",
    "execute_refine",
    "execute_run",
    "execute_transcribe",
    "get_application_paths",
    "list_models",
    "load_options",
    "plan_operation",
    "prepare_asr_model",
    "process_media",
    "refine_srt",
    "render_options_toml",
    "resolve_options",
    "run_doctor",
    "run_files",
    "save_options",
    "transcribe_files",
    "with_asr_profile",
    "with_keep_workdir",
]
